version:
  '2'
services:
  darktable:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        DARKTABLE_TAG: release-2.4.3
    image: darktable-alpine:2.4.3
    container_name: darktable.docker
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
#      - ./config:/home/darktable/.config/darktable
#      - /mnt/host/photos:/home/darktable/pictures
      # Xserver socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
